[tox]
no_package = True
skip_missing_interpreters = True
env_list = lint, static
min_version = 4.0.0

[testenv:lint]
deps = ruff
commands =
    ruff check src tests
    ruff format --check --diff src tests

[testenv:static]
deps =
    pyright
    -r requirements.txt
commands = pyright

[testenv:integration]
deps =
    jubilant>=1.8,<2
    pytest
    pytest-jubilant>=2.0.1,<3
pass_env =
    ATHENA_APP_IMAGE
    CHARM_PATH
    HOME
    PATH
    JUJU_DATA
commands = pytest -v -s --tb native tests/integration
