\if :{?WORKER_ROLE_NAME}
\else
  \echo 'WORKER_ROLE_NAME is required'
  \quit 1
\endif

-- The web process installs pg-boss into this schema on startup, which can follow this grant.
CREATE SCHEMA IF NOT EXISTS pgboss;

SELECT format('GRANT USAGE ON SCHEMA public TO %I', :'WORKER_ROLE_NAME')
\gexec
SELECT format(
  'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO %I',
  :'WORKER_ROLE_NAME'
)
\gexec
SELECT format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', :'WORKER_ROLE_NAME')
\gexec
SELECT format(
  'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I',
  :'WORKER_ROLE_NAME'
)
\gexec
SELECT format(
  'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO %I',
  :'WORKER_ROLE_NAME'
)
\gexec

SELECT format('GRANT USAGE ON SCHEMA pgboss TO %I', :'WORKER_ROLE_NAME')
\gexec
SELECT format(
  'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pgboss TO %I',
  :'WORKER_ROLE_NAME'
)
\gexec
SELECT format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA pgboss TO %I', :'WORKER_ROLE_NAME')
\gexec
SELECT format(
  'ALTER DEFAULT PRIVILEGES IN SCHEMA pgboss GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I',
  :'WORKER_ROLE_NAME'
)
\gexec
SELECT format(
  'ALTER DEFAULT PRIVILEGES IN SCHEMA pgboss GRANT USAGE, SELECT ON SEQUENCES TO %I',
  :'WORKER_ROLE_NAME'
)
\gexec
