issuer: __DEX_ISSUER__

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

web:
  http: 0.0.0.0:5556

grpc:
  addr: 0.0.0.0:5557

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: athena
    name: Athena
    secret: super-secret-value
    redirectURIs:
      - http://athena.localhost/api/authentication/callback
      - https://athena.localhost/api/authentication/callback
      - __DEX_REDIRECT_URI__
      # __DEX_EXTRA_REDIRECT_URIS__

enablePasswordDB: true

staticPasswords:
  - email: dev.user@canonical.com
    hash: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
    username: devuser
    userID: 50f31e6f-26f2-4d93-9fd6-947f8f3f23a8
  - email: loop.member@canonical.com
    hash: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
    username: loopmember
    userID: cac702a3-ac6d-52ce-a159-3076e3005cf1