issuer: __DEX_ISSUER__

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

web:
  http: 0.0.0.0:5556

grpc:
  addr: 0.0.0.0:5557

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: athena
    name: Athena
    secret: __DEX_CLIENT_SECRET__
    redirectURIs:
      - http://athena.localhost/api/authentication/callback
      - https://athena.localhost/api/authentication/callback
      - __DEX_REDIRECT_URI__
      # __DEX_EXTRA_REDIRECT_URIS__

enablePasswordDB: true